# Generated by Django 3.0.8 on 2020-07-18 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appacounts', '0002_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='custumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appacounts.custumer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appacounts.product'),
        ),
    ]
