# Generated by Django 3.0.8 on 2020-07-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appacounts', '0004_auto_20200718_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='appacounts.Tag'),
        ),
    ]
