# Generated by Django 3.0.8 on 2020-07-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appacounts', '0007_custumer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
